---
# Per environment values which override defaults in hmpps-prisoner-monies-send-money-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-monies-send-money-dev.hmpps.service.justice.gov.uk

  env:
    NODE_ENV: 'development'
    INGRESS_URL: "https://prisoner-monies-send-money-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://template-kotlin-dev.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"
    # Extra ones
    SEND_MONEY_URL: "https://send-money-test.prisoner-money.service.justice.gov.uk/"

generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
